

PASS Test calling waitUntil in a different task without an existing extension throws 
PASS Test calling waitUntil in a different microtask without an existing extension throws 
PASS Test calling waitUntil in a different task with an existing extension succeeds 
FAIL Test calling waitUntil with an existing extension promise handler succeeds assert_unreached: unexpected rejection: assert_equals: expected "OK" but got "InvalidStateError" Reached unreachable code
PASS Test calling waitUntil at the end of the microtask turn throws 
PASS Test calling waitUntil after the current extension expired in a different task fails 
PASS Test calling waitUntil on a script constructed ExtendableEvent throws exception 
PASS Test calling waitUntil asynchronously with pending respondWith promise. 
FAIL Test calling waitUntil synchronously inside microtask of respondWith promise. assert_unreached: unexpected rejection: assert_equals: expected "OK" but got "InvalidStateError" Reached unreachable code
PASS Test calling waitUntil asynchronously inside microtask of respondWith promise. 

